# Generated by Django 5.0.1 on 2024-02-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_storeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstmodel',
            name='total_amount_of_order',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Итоговая цена'),
        ),
    ]
