# Generated by Django 5.0.1 on 2024-02-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_storeapp', '0003_goodsmodel_image_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsmodel',
            name='image_product',
            field=models.ImageField(blank=True, default='No image', null=True, upload_to='images/'),
        ),
    ]
